---
  - name: Fact Finder
    hosts: csr
    tasks:
      - name: Register Ansible Facts
        setup:
        register: ansible_facts
      - name: Pring Ansible Facts
        debug:
          msg: "{{ ansible_facts}}"
